export const initialState = {
  accountLogIn: JSON.parse(localStorage.getItem("accountLogin")) || null,
  workSpaceName: JSON.parse(localStorage.getItem("workSpaceName")) || "",
  emailInput: "",
  passwordInput: "",
  channelName: "",
  userId: "",
  emailSignUpInput: "",
  password1: "",
  password2: "",
  workSpaceInput: "",
  addUserInput: "",
  searchMemberInput: "",
  messageChannelInput: "",
  messageUserInput: "",
  activeTab: "about",
  allUsers: JSON.parse(localStorage.getItem("allUsers")) || [],
  allChannels: JSON.parse(localStorage.getItem("allChannels")) || [],
  allDirectMessage: JSON.parse(localStorage.getItem("allDirectMessage")) || [],
  selectedUser: JSON.parse(localStorage.getItem("selectedUser")) || null,
  selectedProfile: JSON.parse(localStorage.getItem("selectedProfile")) || null,
  isAuthenticated: JSON.parse(localStorage.getItem("isAuthenticated")) || false,
  filteredAllUsers: [],
  filteredListMember: [],
  channelListMember: [],
  channelMessages: [],
  userMessages: [],
  numbersOfUser: 0,
  isOpenChannelForm: false,
  isOpenAddUserChannel: false,
  isOpenAddUserForm: false,
  isProfileOpen: false,
  isOpenWorkSpace: false,
  isDirectMessageOpen: false,
  isOpenLink: false,
  ismessageUserInput: false,
  ismessageChannelInput: false,
  isOpenSideBar: false,
};
