export const initialStateLogIn = {
  accountList: JSON.parse(localStorage.getItem("accountList")) || [
    {
      id: 1,
      fullName: "Christian Patrick Nebab",
      email: "dongyang00016@gmail.com",
      password: "pat123",
      channelList: [],
      selectedChannel: null,
    },
    {
      id: 2,
      fullName: "Jeff Binas",
      email: "jeff@gmail.com",
      password: "jeff123",
      channelList: [],
      selectedChannel: null,
    },
  ],
  logInAccount: JSON.parse(localStorage.getItem("logInAccount")) || null,
  channelName: "",
  user: "",
  passwordInput: "",
  emailInput: "",
  fullNameInput: "",
  emailSignUpInput: "",
  password1SignUpInput: "",
  password2SignUpInput: "",
  isOpenChannelForm: false,
  isOpenAddUserForm: false,
};
