export const initialState = {
  accountLogIn: JSON.parse(localStorage.getItem("accountLogin")) || null,
  emailInput: "",
  passwordInput: "",
  channelName: "",
  workSpaceName: "",
  userId: "",
  emailSignUpInput: "",
  password1: "",
  password2: "",
  workSpaceInput: "",
  addUserInput: "",
  searchMemberInput: "",
  numbersOfUser: 0,
  allUsers: [],
  allChannelUserList: [],
  filteredListMember: [],
  getAllChannels: JSON.parse(localStorage.getItem("getAllChannels")) || [],
  selectedUser: JSON.parse(localStorage.getItem("selectedUser")) || null,
  isloggedIn: JSON.parse(localStorage.getItem("isloggedIn")) || false,
  isOpenChannelForm: false,
  isOpenAddUserChannel: false,
  isOpenAddUserForm: false,
  isProfileOpen: false,
  isOpenWorkSpace: false,
};
